config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :banners
    resources :admin_users

    root to: "users#index"
  end

  resources :banners
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
  enum status: {submitted: 0, assigned: 1, completed: 2, ops_qa: 3, product_qa: 4, completed: 5, rejected: 6 }
  belongs_to :user, optional: true
  validates_presence_of :start_date, :end_date, :location, :image

  mount_uploader :image, ImageUploader

  scope :banners_by, ->(user) { where(user_id: user.id) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :banners
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name
    last_name.upcase + ", " + first_name.upcase
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
       unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access this page."
        redirect_to(root_path)
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/banners_controller.rb
module Admin
  class BannersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Banner.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Banner.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :authenticate_user!


  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  def index
    @banners = Banner.banners_by(current_user).page(params[:page]).per(10)
  end

  def new
    @banner = Banner.new
  end

  def create
    @banner = Banner.new(banner_params)
    @banner.user_id = current_user.id

    if @banner.save
      redirect_to @banner, notice: 'Your banner was created successfully'
    else
      render :new
    end
  end

  def edit
    authorize @banner
  end

  def update
    authorize @banner

    if @banner.update(banner_params)
      redirect_to @banner, notice: 'Your banner was edited successfully'
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @banner.delete
    redirect_to banners_path, notice: 'Your banner was deleted successfully'
  end

  private

    def banner_params
      params.require(:banner).permit(:start_date, :end_date, :location, :headline, :subcopy, :image, :status)
    end

    def set_banner
      @banner = Banner.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def homepage
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_types
    ['AdminUser']
  end

  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/banners_helper.rb
module BannersHelper

  def status_label status
      status_span_generator status
  end

  private

  def status_span_generator status
    case status
      when 'submitted'
        content_tag(:span, status.titleize, class: 'label label-primary')
      when 'assigned'
        content_tag(:span, status.titleize, class: 'label label-info')
      when 'ops-qa'
        content_tag(:span, status.titleize, class: 'label label-primary')
      when 'product-qa'
        content_tag(:span, status.titleize, class: 'label label-primary')
      when 'completed'
        content_tag(:span, status.titleize, class: 'label label-success')
      when 'rejected'
        content_tag(:span, status.titleize, class: 'label label-danger')
    end
  end
end

app/views/banners/_banner.html.erb
 <tr>
   <td>
     <%= banner.id %>
   </td>
   <td>
     <%= banner.start_date %>
   </td>
   <td>
     <%= banner.end_date %>
   </td>
   <td>
     <%= banner.user.full_name %>
   </td>
   <td>
     <%= banner.location %>
   </td>
   <td>
     <%= link_to truncate(banner.headline), banner %>
   </td>
   <td>
     <%= image_tag(banner.image.url(:thumb).to_s) %>
   </td>
   <td>
     <%= status_label banner.status %>
   </td>
   <td>
     <%= link_to '', edit_banner_path(banner), id: "edit_#{banner.id}", class: 'glyphicon glyphicon-pencil class: index-icons' if policy(banner).update? %>
   </td>
   <td>
     <%= link_to '', banner_path(banner), method: :delete, id: "delete_post_#{banner.id}_from_index", class: 'glyphicon glyphicon-trash class: index-icons', data: {confirm: 'Are you sure' } %>
   </td>
 </tr>

app/views/banners/_form.html.erb
<%= form_for @banner, class: "form" do |f| %>

  <% if @banner.errors.any? %>
    <% @banner.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Ops App Notifications", sticky: false) %>
    <% end %>
  <% end %>


  <div class="form-group">
    <%= f.label :start_date, class: "col-sm-2 control-label" %>
    <%= f.date_field :start_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :end_date, class: "col-sm-2 control-label" %>
    <%= f.date_field :end_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location, class: "col-sm-2 control-label" %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :headline, class: "col-sm-2 control-label" %>
    <%= f.text_area :headline, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :subcopy, class: "col-sm-2 control-label" %>
    <%= f.text_area :subcopy, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">

    <%= render partial: 'status', locals: {f: f} if current_user.type == "AdminUser" %>

    <%= f.submit 'Save', class: "btn btn-primary btn-block" %>
  </div>

<% end %>



<form class="form-inline" role="form">
   <div class="form-group">
      <label for="name">Name</label>
    <input type="name" class="form-control" id="name" placeholder="Enter name">
   </div>
   <div class="form-group">
      <label for="email">Email</label>
    <input type="email" class="form-control" id="email" placeholder="Enter email">
 </div>
</form>

app/views/banners/_status.html.erb
<div class='form-group'>

  <%= f.radio_button :status, 'submitted' %>
  <%= f.label :status, 'Submitted' %>

  <%= f.radio_button :status, 'assigned' %>
  <%= f.label :status, 'Assigned' %>

  <%= f.radio_button :status, 'ops_qa' %>
  <%= f.label :status, 'Ops QA' %>

  <%= f.radio_button :status, 'product_qa' %>
  <%= f.label :status, 'Product QA' %>

  <%= f.radio_button :status, 'completed' %>
  <%= f.label :status, 'Completed' %>

  <%= f.radio_button :status, 'rejected' %>
  <%= f.label :status, 'Rejected' %>

</div>

app/views/banners/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/banners/index.html.erb
<h1>Banners</h1>

<p><%= link_to "Add New Banner", new_banner_path, id: 'new_banner_from_index', class: "btn btn-danger" %></p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>
        #
      </th>
      <th>
        Start Date
      </th>
      <th>
        End Date
      </th>
      <th>
        User
      </th>
      <th>
        location
      </th>
      <th>
        Headline
      </th>
      <th>
        Image
      </th>
      <th>
        Status
      </th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody id="banners">
    <%= render @banners %>
  </tbody>
</table>

<div id="paginator">
  <%= paginate @banners, remote: true %>
</div>

app/views/banners/index.js.erb
$('#banners').html('<%= escape_javascript render(@banners) %>');
$('#paginator').html('<%= escape_javascript(paginate(@banners, remote: true).to_s) %>');

app/views/banners/new.html.erb
<h1>New Banner Submission</h1>

<%= render 'form' %>

app/views/banners/show.html.erb
<div>
  <h2><span>Headline: </span><%= @banner.headline %></h2>
</div>

<div>
  <h3><span>Subcopy: </span><%= @banner.subcopy %></h3>
</div><br>

<div class='well'>
  <div>
    <h4><span>Start Date: </span><%= @banner.start_date %></h4>
  </div>

  <div>
    <h4><span>End Date: </span><%= @banner.end_date %></h4>
  </div>

  <div>
    <h4><span>Location: </span><%= @banner.location %></h4>
  </div>

  <div>
    <h4><span>Status: </span><%= @banner.status %></h4>
  </div>

  <div>
    <h4><span>User: </span><%= @banner.user.full_name %></h4>
  </div>

  <div>
    <h4><span>Image: </span><%= image_tag(@banner.image.url(:thumb).to_s) %></h4>
  </div>
</div>

<%= link_to 'Edit', edit_banner_path(@banner), class: 'btn btn-primary' if policy(@banner).update? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SleepingSheeplesslyV4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render 'shared/nav' %>
          <%= yield %>
        </div>
      </div>
    </div>

     <%= render 'shared/alerts' %>

  </body>
</html>

app/views/shared/_alerts.html.erb
 <% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Ops App Alert", sticky: false) %>
  <% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Ops App Error", sticky: false) %>
  <% else %>
  <%= js add_gritter(flash[:notice], title: "Ops App Notification", sticky: false) %>
<% end %>

app/views/shared/_nav.html.erb
<div class="logo">
  <h1>Sleeping Sheeplessly</h1>
</div>

<!-- TODO -->
<% if current_user %>
  <ul class="nav nav-tabs">
    <li class="<%= active?(root_path) %>">
      <%= link_to "Home", root_path %>
    </li>
    <li class="<%= active?(banners_path) %>">
      <%= link_to "Banners", banners_path %>
    </li>
    <li class="disabled">
      <a href="#">Messages</a>
    </li>
    <li class="dropdown pull-right">
       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
      <ul class="dropdown-menu">

        <!-- TODO -->
        <% if current_user.try(:type) == "AdminUser" %>
        <li>
          <%= link_to "Admin Dashboard", admin_root_path %>
        </li>
        <li class="divider"></li>
        <% end %>
        <!-- TODO -->

        <li>
           <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>
<!-- TODO -->